### ISSUE TITLE
Is this instruction unnecessary ?

### ISSUE THREAD

**Issue by embeddedmz** [Sensirion/embedded-i2c-sht4x#1]
I really like the simplicity of this repo.

In "sensirion_i2c.c" sensirion_i2c_read_words, I think this loop is unnecessary :

```
for (i = 0; i < num_words; ++i) {
        const uint8_t* word_bytes = (uint8_t*)&data_words[i];
        data_words[i] = ((uint16_t)word_bytes[0] << 8) | word_bytes[1];
    }
```

Isn't it ?

**Comment by psachs** [comment]
the sensirion_i2c.c is a generic implementation of the I2C communication that we use (and is shared) in all our I2C drivers. The for loop is therefore necessary in some cases.
The sensirion_i2c_read_words method is not used in this driver at all, so in this context you are right that the for loop is not necessary ;-)
