### ISSUE TITLE
new tag or release?

### ISSUE THREAD

**Issue by morse-miladmohtashamirad** [Sensirion/embedded-i2c-sht4x#5]
Probably it's a good time to have a new release tag. ;) 
Looks like that there's been some changes since the latest tag (0.1.0) which was 3 years ago.
Kind regards.

**Comment by sdmueller** [comment]
Hi @morse-miladmohtashamirad 

The tags should now be actually in line with the changelog.
Thanks for the heads up :smiley:

**Comment by morse-miladmohtashamirad** [comment]
My pleasure. 
Thanks for tagging. :)
